version: "3.8"
services:
  frontend:
    build:
      context: ./vue-frontend
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./EnergyConsumptionOptimization
    ports:
      - "5069:5069"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

# docker-compose -f docker-compose.prod.yml up --build -d
